#!/bin/sh
cd "${0%/*}" || exit 1

. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

for f in ./*; do
    name=$(basename "$f")
    case "$name" in
        *" "*)
            echo "Refusing to run: case directory contains a filename with spaces: $name"
            echo "Rename it first. OpenFOAM 13 on this machine aborts on such filenames."
            exit 1
            ;;
    esac
done

runApplication blockMesh
rm -rf 0/polyMesh
cp -r constant/polyMesh 0/
runApplication setFields
runApplication foamRun -solver incompressibleVoF
