#!/bin/sh
cd "${0%/*}" || exit 1

. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

for f in ./*; do
    name=$(basename "$f")
    case "$name" in
        *" "*)
            echo "Refusing to run: case directory contains a filename with spaces: $name"
            exit 1
            ;;
    esac
done

rm -f log.blockMesh log.foamRun
runApplication blockMesh
runApplication foamRun -solver solidDisplacement
